name: Run OPA Tests
on: [push]
jobs:
  Policy-Validation:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: |
        terraform init

    - name: Terraform Plan
      id: plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform plan -out=tfplan
        terraform show -json tfplan > tfplan.json

    - name: Run OPA Policy Validation
      run: |
        opa exec --decision exemplo/tags/deny_missing_tags  --bundle policy/ tfplan.json
