name: Run OPA Tests
on: [push]
jobs:
  Policy-Validation:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Set AWS Creds
      uses: aws-actions/configure-aws-credentials@v4

    - name: Terraform Init
      id: init
      shell: bash
      run: |
        terraform init

    - name: Terraform Plan
      id: plan
      shell: bash
      run: |
        terraform plan -out=tfplan
        terraform show -json tfplan > tfplan.json

    - name: Run OPA Policy Validation
      run: opa exec --decision exemplo/tags/deny_missing_tags  --bundle policy/ tfplan.json
